### ISSUE TITLE
Localization within border ctrl seems to cause Memory Leak

### ISSUE THREAD

**Issue by Skuriles** [XAMLMarkupExtensions/WPFLocalizeExtension#314] opened 2021-10-05 07:47 UTC
**Describe the bug**
We used lex:Loc extension to translate a TextBlock within a BorderCtrl. After checking the Memory consumption with JetBrains dotMemory tool we saw a slightly increase of the "inner" dictionary of ParentNotifiers used in public static T GetValueOrRegisterParentNotifier<T> of ParentChangedNotifierHelper.
It looks like the references are set to "null" before the ParentNotifier Dictionary is updated correctly. Then the key will no longer be found and added again. 
We tried the same with a Label Control inside a Border Ctrl but this made no change to the memory. 
As the parent control has multiple instances the dictionary was over 10.000 entries after few hours.
We've ended up to use a Label and manipulate the direct border of the Label instead of using a derived class from Border (which worked)

**To Reproduce**
We use default Resource Manager to handle translations!
We used a simple BorderEx Control (derived from Border Control) with the following XAML.
The Control was within another Control which was dynamically created and deleted every few seconds. All other ParentNotifiers were handled correctly but not that one of the TextBlock.

```
<Border ....>
    <Border.Resources>
        <Style TargetType="slot:BorderEx">
            ...
    </Border.Resources>

    <TextBlock Text="{lex:Loc disabled}" HorizontalAlignment="Center" VerticalAlignment="Center" 
               Visibility="{Binding ShowSelectionBorderDisabled, RelativeSource={RelativeSource FindAncestor, AncestorType={x:Type slot:BorderEx}}, Converter={StaticResource BoolToVisibilityConverter}}" />

</Border>
```
To reproduce it should be enough to create a UserControl, put the Border Control in it and regularly dismiss and newly create the userControl to see the growing Dictionary. I did not investigate it deeper and I can't share more of the Code. Maybe it has something to do with the whole code we use. Just wanted to give a hint, because this one was a major issue on our side as any memory leak can have huge effects.

**Expected behavior**
All ParentNotifier should be cleared when Parent is garbage collected. 

**Enviroment (please complete the following information):**
 - OS: Windows 10 
 - .NET Framework: [NET47]
 - Latest Release of WPFLocalizeExtension

**Comment by konne** [comment] 2021-11-14 18:15
@Karnah do you have a chance to check this?

**Comment by narcis-sy** [comment] 2021-12-01 09:46
Happens to me also. Unrelated to borders. Closures of `ParentChangedNotifierHelper` are being leaked

I think it's related to access of the closure generated classes which are being kept in memory by the delegate which is hold in mem by a gc root (the xaml extensions: `ParentChangedNotifier.OnParentChangedList`)

![image](https://user-images.githubusercontent.com/67704105/144206632-fd117002-eb62-4e52-8cb4-9d0cdf9e9e6c.png)

![image](https://user-images.githubusercontent.com/67704105/144206922-9c0147bd-9d21-4da0-9d48-f657cd0f9222.png)

![image](https://user-images.githubusercontent.com/67704105/144206124-5aa00d80-f1f8-4c0a-ab22-0f3c9bfbd5d7.png)

I guess the solution would be to remove the closure, not sure if it can be done.

One other solution I used recently for exactly this scenario, exactly for WPF localization. I wanted to create a Binding which reacts to the Localization changed event. The event is a static weak event. I didn't want my handler to interfere with the lifetime of dependency object, but I want it to be tied to it. When the dependency object is removed, so should this event handler.
It turns out .Net has the perfect solution for this:  [ConditionalWeakTable](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.conditionalweaktable-2?view=net-6.0). With it you can tie the lifetime of your handler to the lifetime of your dependency object.

Here is a sample of my Culture Binding. Maybe it will be useful to someone else as well.

```csharp
public class CultureBindingExtension : MarkupExtension
{
    private readonly Binding _inner;
    public bool ShouldSerializeFallbackValue() => _inner.ShouldSerializeFallbackValue();

    public bool ShouldSerializeTargetNullValue() => _inner.ShouldSerializeTargetNullValue();

    public object FallbackValue
    {
        get => _inner.FallbackValue;
        set => _inner.FallbackValue = value;
    }

    public string StringFormat
    {
        get => _inner.StringFormat;
        set => _inner.StringFormat = value;
    }

    public object TargetNullValue
    {
        get => _inner.TargetNullValue;
        set => _inner.TargetNullValue = value;
    }

    public string BindingGroupName
    {
        get => _inner.BindingGroupName;
        set => _inner.BindingGroupName = value;
    }

    public int Delay
    {
        get => _inner.Delay;
        set => _inner.Delay = value;
    }

    public bool ShouldSerializeValidationRules() => _inner.ShouldSerializeValidationRules();

    public bool ShouldSerializePath() => _inner.ShouldSerializePath();

    public bool ShouldSerializeSource() => _inner.ShouldSerializeSource();

    public Collection<ValidationRule> ValidationRules => _inner.ValidationRules;

    public bool ValidatesOnExceptions
    {
        get => _inner.ValidatesOnExceptions;
        set => _inner.ValidatesOnExceptions = value;
    }

    public bool ValidatesOnDataErrors
    {
        get => _inner.ValidatesOnDataErrors;
        set => _inner.ValidatesOnDataErrors = value;
    }

    public bool ValidatesOnNotifyDataErrors
    {
        get => _inner.ValidatesOnNotifyDataErrors;
        set => _inner.ValidatesOnNotifyDataErrors = value;
    }

    public string XPath
    {
        get => _inner.XPath;
        set => _inner.XPath = value;
    }

    public BindingMode Mode
    {
        get => _inner.Mode;
        set => _inner.Mode = value;
    }

    public UpdateSourceTrigger UpdateSourceTrigger
    {
        get => _inner.UpdateSourceTrigger;
        set => _inner.UpdateSourceTrigger = value;
    }

    public bool NotifyOnSourceUpdated
    {
        get => _inner.NotifyOnSourceUpdated;
        set => _inner.NotifyOnSourceUpdated = value;
    }

    public bool NotifyOnTargetUpdated
    {
        get => _inner.NotifyOnTargetUpdated;
        set => _inner.NotifyOnTargetUpdated = value;
    }

    public bool NotifyOnValidationError
    {
        get => _inner.NotifyOnValidationError;
        set => _inner.NotifyOnValidationError = value;
    }

    public object ConverterParameter
    {
        get => _inner.ConverterParameter;
        set => _inner.ConverterParameter = value;
    }

    public CultureInfo ConverterCulture
    {
        get => _inner.ConverterCulture;
        set => _inner.ConverterCulture = value;
    }

    public object Source
    {
        get => _inner.Source;
        set => _inner.Source = value;
    }

    public RelativeSource RelativeSource
    {
        get => _inner.RelativeSource;
        set => _inner.RelativeSource = value;
    }

    public string ElementName
    {
        get => _inner.ElementName;
        set => _inner.ElementName = value;
    }

    public bool IsAsync
    {
        get => _inner.IsAsync;
        set => _inner.IsAsync = value;
    }

    public object AsyncState
    {
        get => _inner.AsyncState;
        set => _inner.AsyncState = value;
    }

    public bool BindsDirectlyToSource
    {
        get => _inner.BindsDirectlyToSource;
        set => _inner.BindsDirectlyToSource = value;
    }

    public UpdateSourceExceptionFilterCallback UpdateSourceExceptionFilter
    {
        get => _inner.UpdateSourceExceptionFilter;
        set => _inner.UpdateSourceExceptionFilter = value;
    }

    public CultureBindingExtension()
    {
        _inner = new Binding();
    }

    public CultureBindingExtension(PropertyPath path)
    {
        _inner = new Binding();
        Path = path;
    }

    public IValueConverter Converter
    {
        get => _inner.Converter;
        set => _inner.Converter = value;
    }

    public PropertyPath Path
    {
        get => _inner.Path;
        set => _inner.Path = value;
    }

    /// <summary>
    /// Note: Tested for memory leaks, works alright.
    /// </summary>
    private static readonly ConditionalWeakTable<DependencyObject, CultureChangedListener> Listeners = new();

    public override object ProvideValue(IServiceProvider serviceProvider)
    {
        var target = (IProvideValueTarget)serviceProvider.GetService(typeof(IProvideValueTarget));

        if (target.TargetObject is not DependencyObject targetObject || target.TargetProperty is not DependencyProperty property)
            return this;

        if (_inner.ProvideValue(serviceProvider) is not BindingExpressionBase expression)
            return this;

        Listeners.Add(targetObject, new CultureChangedListener(targetObject, property));
        
        return expression;
    }
}

/// <summary>
/// Class which holds the weak event listener for culture changed.
/// </summary>
public class CultureChangedListener
{
    private readonly WeakReference<DependencyObject> _targetObject;
    private readonly WeakReference<DependencyProperty> _targetTargetProperty;
    
    public CultureChangedListener(DependencyObject targetObject, DependencyProperty targetTargetProperty)
    {
        _targetObject = new WeakReference<DependencyObject>(targetObject);
        _targetTargetProperty = new WeakReference<DependencyProperty>(targetTargetProperty);

        AppGlobalization.CultureChangedWeak += CultureChangedListener_CultureChangedWeak;
    }

    private void CultureChangedListener_CultureChangedWeak(object o, CultureChanged e)
    {
        var dispatcher = Application.Current.Dispatcher;

        // Note: DO NOT await, it will revert the culture change
        // Note: Event is always raised on a non UI thread.
        dispatcher.InvokeAsync(() =>
        {
            if (_targetObject.TryGetTarget(out var target) && _targetTargetProperty.TryGetTarget(out var property))
            {
                // Note: We need to always get the BindingExpressionBase because it will get collected when using this Binding in a ControlTemplate
                var bindingExpressionBase = BindingOperations.GetBindingExpressionBase(target, property);

                // TODO: Does not update the source, so OneWayToSource is not really supported.
                
                bindingExpressionBase?.UpdateTarget();
            }
            else
            {
                AppGlobalization.CultureChangedWeak -= CultureChangedListener_CultureChangedWeak;
            }
        }, DispatcherPriority.DataBind);
    }
}
```
What I don't like to both solutions `Dictionary<WeakReference, List<Action>>` or `ConditionalWeakTable<DependencyObject, CultureChangedListener>` is that they both will keep empty shells as items, e.g entries that have weak references pointing to collected objects. Should be peanuts in terms of memory usage, a couple of bytes. I guess one other approach you could employ is something like [WeakEventManager](https://docs.microsoft.com/en-us/dotnet/api/system.windows.weakeventmanager?view=windowsdesktop-6.0) does, with cleanup on the dispatcher idle. Of course that works only for WPF Apps.

Hope this helps someone.

Option #2 
Another idea would be to remove the `ParentChangedNotifier` when the `frameworkElement` is unloaded, something along the lines.
![image](https://user-images.githubusercontent.com/67704105/144210799-ef8eb93d-c4ba-4744-b4f8-10448135bf33.png)


P.S Good news is there is only 1 leak :)
![image](https://user-images.githubusercontent.com/67704105/144209942-9a122c7b-23ab-4a7f-b4a3-f51c1cf931bf.png)

**Comment by konne** [comment] 2021-12-30 22:45
@Karnah do you have a chance to check this?

**Comment by Karnah** [comment] 2021-12-31 09:04
Hello. @konne, I'll try to check this next week

**Comment by Karnah** [comment] 2022-01-14 13:23
@narcis-sy, could you create a separate project which shows memory leaking? I can't fully understand how you do it. 
I reproduced similar situation when created controls code-behind:
``` c#
var ex = new LocExtension("Hello World");
var tb = new TextBlock();
ex.ProvideValue(new Target(tb, TextBlock.TextProperty));
```
But I want to be sure that your case looks the same.

@konne 
I've found two problems and solutions for them:
1. 
https://github.com/XAMLMarkupExtensions/WPFLocalizeExtension/blob/833970d3cd6dd97ca15a18bc38137147879d9b54/src/Engine/ParentNotifiers.cs#L24
This collection has to be cleaned if `key.Target` is `null`. `Value` is better to store without `WeakReference<>` and call `Dispose` before removing. Probably the best moment for collection checking is `ParentNotifiers.Remove`, because we go through collection to find element to remove.
2. 
[ParentChangedNotifier.Dispose](https://github.com/XAMLMarkupExtensions/XAMLMarkupExtensions/blob/98733d9ca187a327d481c15f86b1c5947ed05d39/src/Base/ParentChangedNotifier.cs#L141)
If an element has already been disposed - we don't remove the item from static `OnParentChangedList`. 

I'll create two PRs to each repository. But I'd like to test it before.

@narcis-sy and @Skuriles thanks a lot for your research. You did great work.

**Comment by narcis-sy** [comment] 2022-01-14 15:55
Hello

You can find a reproduction repo [here](https://github.com/narcis-sy/wpflocalize_memory_leak).

Here is how to reproduce it:

```
 - Start App
 - Click on the Add button 10 times.
 - Change the language a couple of times
 - Click remove button 10 times 
 - Take memory snapshot
 - Look for objects of type with name containing "parentchanged"
	e.g WPFLocalizeExtension.Providers.ParentChangedNotifierHelper+<>c__DisplayClass0_0<String>
        WeakReference<XAMLMarkupExtensions.Base.ParentChangedNotifier> 
 - At least 20-30 instances should still be alive
		ParentChangedNotifierHelper+<>c__DisplayClass0_0<String>   <== this would be the closure generated class
		WeakReference<XAMLMarkupExtensions.Base.ParentChangedNotifier>
```
Start of the app state
![image](https://user-images.githubusercontent.com/67704105/149543648-3fd08327-f64c-4631-a300-6edd01faeb05.png)

After adding 10 items

![image](https://user-images.githubusercontent.com/67704105/149543785-6bcdd1f7-4641-4165-a922-df3235ec4910.png)

After removing all of the items

![image](https://user-images.githubusercontent.com/67704105/149543894-cc776305-2d3e-4648-b0b4-c3cfd2d33581.png)

All good until now.

Lets add 4 items and change the language a couple of times

![image](https://user-images.githubusercontent.com/67704105/149544177-95a90447-ad50-4364-b353-515d532ad383.png)

Closures started to appear.

Now remove them and take 2 snapshot to simulate 2 x GC.Collect, making sure nothing would be on the Gen0 or finalizer queue

![image](https://user-images.githubusercontent.com/67704105/149544477-6125321b-e570-44e1-97a5-1621a1c70c01.png)

Voila! Memory leaks :) 

I added a data template and also a style because i thought it only reproduces if there is a style involved, but then I got to reproduce it without the style as well.

Hope this helps. Cheers!

**Comment by konne** [comment] 2022-01-15 10:29
@Skuriles thanks for the great reproduce howto
@Karnah great please add the PRs

**Comment by Karnah** [comment] 2022-01-16 16:46
@konne, did it

@narcis-sy, I debugged it and found a bit another way of reproducing. After removing items, I called to change the language. There were a lot of controls that were detached from Visual Tree and for them created notifiers. Now if these controls are collected by GC (it's important, I created new button in your project to call GC.Collect()) and call `Add` then all dead items will be removed.

**Comment by konne** [comment] 2022-01-16 17:53
@Skuriles @narcis-sy @Karnah 
please test the new 3.9.3 Release. It should be in around 20min available on nuget
https://github.com/XAMLMarkupExtensions/WPFLocalizeExtension/releases/tag/3.9.3

I will close the issue for now. If you still find issues, just reopen.

**Closed by konne** 2022-01-16 17:53 UTC

**Comment by Karnah** [comment] 2022-01-16 17:59
@konne, [this PR](https://github.com/XAMLMarkupExtensions/XAMLMarkupExtensions/pull/124) is also needed to fix this bug.

**Comment by konne** [comment] 2022-01-17 07:29
@Skuriles @narcis-sy @Karnah
sorry I didn't update the underlying Lib. Fixed, so please test the new 3.9.4

**Comment by narcis-sy** [comment] 2022-01-17 08:46
For me it still happens with version 3.9.4. Added button for 2x GC.Collect as well, although I am sure the Take Snapshot does a GC.Collect as well.

![image](https://user-images.githubusercontent.com/67704105/149736786-5304c4ec-9001-44e2-9ee0-288ec17dab4c.png)

**Comment by Karnah** [comment] 2022-01-17 09:03
@narcis-sy, I've tested your project:
Snapshot 1:
![image](https://user-images.githubusercontent.com/6525732/149738800-688ccc64-edcf-4cfd-b0a9-1e282b39c674.png)
Snapshot 2:
![image](https://user-images.githubusercontent.com/6525732/149738859-36e7bedb-6fa0-4c33-bc59-5a50f407312e.png)

Did you call 'Add' after collecting? These items removing only when adding new. It's the easiest way to control this collection, and in a real application it won't be a problem.

**Comment by narcis-sy** [comment] 2022-01-17 09:31
Steps:

1. 3 x Add
2. 2 x Change
3. 4 x Remove
4. 1 x Collect 
5. Snapshot
![image](https://user-images.githubusercontent.com/67704105/149743260-0f9b6915-e7e3-4bdf-aa28-29b0a83b7cb2.png)

Works, but the adding/removing and changing while there are still some items in the list doesn't

Steps:
1. 6 x Add
2. 2 x Change
3. 2 x Remove
4. 3 x Add
5. 3 x Change
6. remove all
5. 1 x Collect 
6. Snapshot

![image](https://user-images.githubusercontent.com/67704105/149743068-9ec145df-7e46-4bba-96bb-380a833f479e.png)

I could also reproduce it as:

1. 3 x Add
2. 2 x Change
3.  Remove all
4. Change language
4. 1 x Collect 
5. Snapshot

**Comment by narcis-sy** [comment] 2022-01-17 09:32
Added debug output logs for easier repro. 

![image](https://user-images.githubusercontent.com/67704105/149744027-60b59866-709c-4223-81e6-8bf460bc620f.png)

**Comment by narcis-sy** [comment] 2022-01-17 09:38
I've added a button "Scenario1" to execute the click sequence.

I consistently get 2 memory leaks for this scenario.

![image](https://user-images.githubusercontent.com/67704105/149744879-354562ce-7d4b-44d6-9a42-a465218d0d6d.png)

**Comment by Karnah** [comment] 2022-01-17 09:42
@narcis-sy, please, add call 'Add' after 'Collect'. As I said, a collection of `WPFLocalizeExtension.Providers.ParentChangedNotifierHelper+<>c__DisplayClass0_0<System.String>` cleared only in specific moments of time. In a real application, these moments will be quite ofter for not to worry about memory leaks.

**Comment by narcis-sy** [comment] 2022-01-17 11:39
@Karnah 

Added Add after collect. Still results in increase of memory leaks. I clicked Scenario 1 a couple of times:

![image](https://user-images.githubusercontent.com/67704105/149762165-d7c7071f-694d-4be7-a83a-5f3ba34572a8.png)

```
Add
Add
Add
Remove
Remove
Remove
Remove
Change
Change
Change
Collect
Add
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='System.Windows.FrameworkElement', AncestorLevel='1''. BindingExpression:Path=Parent; DataItem=null; target element is 'ContentPresenter' (Name=''); target property is 'Parent' (type 'DependencyObject')
Add
Add
Add
Remove
Remove
Remove
Remove
Change
Change
Change
Collect
Add
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='System.Windows.FrameworkElement', AncestorLevel='1''. BindingExpression:Path=Parent; DataItem=null; target element is 'ContentPresenter' (Name=''); target property is 'Parent' (type 'DependencyObject')
Add
Add
Add
Remove
Remove
Remove
Remove
Change
Change
Change
Collect
Add
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='System.Windows.FrameworkElement', AncestorLevel='1''. BindingExpression:Path=Parent; DataItem=null; target element is 'ContentPresenter' (Name=''); target property is 'Parent' (type 'DependencyObject')
Add
Add
Add
Remove
Remove
Remove
Remove
Change
Change
Change
Collect
Add
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='System.Windows.FrameworkElement', AncestorLevel='1''. BindingExpression:Path=Parent; DataItem=null; target element is 'ContentPresenter' (Name=''); target property is 'Parent' (type 'DependencyObject')
Add
Add
Add
Remove
Remove
Remove
Remove
Change
Change
Change
Collect
Add
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='System.Windows.FrameworkElement', AncestorLevel='1''. BindingExpression:Path=Parent; DataItem=null; target element is 'ContentPresenter' (Name=''); target property is 'Parent' (type 'DependencyObject')
Add
Add
Add
Remove
Remove
Remove
Remove
Change
Change
Change
Collect
Add
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='System.Windows.FrameworkElement', AncestorLevel='1''. BindingExpression:Path=Parent; DataItem=null; target element is 'ContentPresenter' (Name=''); target property is 'Parent' (type 'DependencyObject')
Add
Add
Add
Remove
Remove
Remove
Remove
Change
Change
Change
Collect
Add
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='System.Windows.FrameworkElement', AncestorLevel='1''. BindingExpression:Path=Parent; DataItem=null; target element is 'ContentPresenter' (Name=''); target property is 'Parent' (type 'DependencyObject')
Add
Add
Add
Remove
Remove
Remove
Remove
Change
Change
Change
Collect
Add
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='System.Windows.FrameworkElement', AncestorLevel='1''. BindingExpression:Path=Parent; DataItem=null; target element is 'ContentPresenter' (Name=''); target property is 'Parent' (type 'DependencyObject')
Add
Add
Add
Remove
Remove
Remove
Remove
Change
Change
Change
Collect
Add
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='System.Windows.FrameworkElement', AncestorLevel='1''. BindingExpression:Path=Parent; DataItem=null; target element is 'ContentPresenter' (Name=''); target property is 'Parent' (type 'DependencyObject')
Add
Add
Add
Remove
Remove
Remove
Remove
Change
Change
Change
Collect
Add
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='System.Windows.FrameworkElement', AncestorLevel='1''. BindingExpression:Path=Parent; DataItem=null; target element is 'ContentPresenter' (Name=''); target property is 'Parent' (type 'DependencyObject')
Add
Add
Add
Remove
Remove
Remove
Remove
Change
Change
Change
Collect
Add
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='System.Windows.FrameworkElement', AncestorLevel='1''. BindingExpression:Path=Parent; DataItem=null; target element is 'ContentPresenter' (Name=''); target property is 'Parent' (type 'DependencyObject')

```

Updated the repro as well.

Start app. Click Scenario1 3 times. Snapshot. => 6 objects in memory.
Repeat. 3 x Scenario1. Snapshot => 12 objects in memory

![image](https://user-images.githubusercontent.com/67704105/149763160-ca33c4a1-11f8-46f9-8558-d4cb86e7f4e2.png)

**Comment by narcis-sy** [comment] 2022-01-17 16:08
Weird, I see it doesn't reproduce it on your machine. It does on mine. See 2 separate examples below.
One thing that I remember is that the Visual Studio live tree does affect if it is on, it keeps the elements in mem, not sure how it would affect here, but just fyi.
![sample](https://user-images.githubusercontent.com/67704105/149803751-b04f48d9-3dce-4f8e-a438-7a4003fe8f9c.gif)
![scr](https://user-images.githubusercontent.com/67704105/149803766-f272bd6b-87d7-4556-afa2-34383cc2c060.gif)

**Comment by Karnah** [comment] 2022-01-17 17:54
@narcis-sy, hmm, it's an interesting idea about Live Visual Tree. I wrote code that can help you to track inner collection:
```
private void CheckNotifiers()
{
    Dispatcher.Invoke(() => { }, DispatcherPriority.ApplicationIdle);

    var provider = LocalizeDictionary.Instance.DefaultProvider;
    var parentNotifiersFieldInfo = typeof(ResxLocalizationProvider).GetField("_parentNotifiers", BindingFlags.NonPublic | BindingFlags.Instance);
    var parentNotifiers = (ParentNotifiers)parentNotifiersFieldInfo.GetValue(provider);

    var innerFieldInfo = typeof(ParentNotifiers).GetField("_inner", BindingFlags.NonPublic | BindingFlags.Instance);
    var inner = (Dictionary<WeakReference<DependencyObject>, ParentChangedNotifier>)innerFieldInfo.GetValue(parentNotifiers);

    var count = inner.Count;
    var aliveCount = inner.Keys.Count(k => k.TryGetTarget(out _));
}
```

Please add it to your project and create an output field for it. After this, you can run your application without debug and check how it works. Also, you can check if your controls are alive. This really means that something has reference to them.

**Comment by narcis-sy** [comment] 2022-01-17 19:12
Seems to be working fine if I start without debugging, i dump a couple of times (collect + add) until i get zero count/alive. I then attach the debugger and take a snapshot. It returns to 1. I guess the live visual tree still holds some refs when running directly in debug mode.

Thanks for taking the time to fix it. Cheers!

![image](https://user-images.githubusercontent.com/67704105/149825692-2517e6c4-2831-48ac-97af-5b4917cea3f9.png)
