### ISSUE TITLE
KeyNotFoundException with v3.9.0

### ISSUE THREAD

**Issue by tobe83** [XAMLMarkupExtensions/WPFLocalizeExtension#313] opened 2021-09-07 10:15 UTC
Hello,
since updating to new Version v3.9.0 I get sporadic KeyNotFoundException. Never happened with previous version installed.

the complete exception text:

`System.Windows.Markup.XamlParseException
  HResult=0x80131501
  Nachricht = The specified key was not given in the dictionary.
  Quelle = PresentationFramework
  Stapelüberwachung:
   bei System.Windows.FrameworkTemplate.LoadTemplateXaml(XamlReader templateReader, XamlObjectWriter currentWriter)

  Diese Ausnahme wurde ursprünglich von dieser Aufrufliste ausgelöst:
    System.Collections.Generic.Dictionary<TKey, TValue>.this[TKey].get(TKey)
    XAMLMarkupExtensions.Base.TargetObjectsList.AddTargetObjectProperty(System.WeakReference, object, System.Type, int) in TargetObjectsList.cs
    XAMLMarkupExtensions.Base.NestedMarkupExtension.ProvideValue(System.IServiceProvider) in NestedMarkupExtension.cs
    System.Windows.StyleHelper.GetInstanceValue(System.Windows.UncommonField<System.Collections.Specialized.HybridDictionary[]>, System.Windows.DependencyObject, System.Windows.FrameworkElement, System.Windows.FrameworkContentElement, int, System.Windows.DependencyProperty, int, ref System.Windows.EffectiveValueEntry)
    System.Windows.StyleHelper.GetChildValueHelper(System.Windows.UncommonField<System.Collections.Specialized.HybridDictionary[]>, ref MS.Utility.ItemStructList<System.Windows.ChildValueLookup>, System.Windows.DependencyProperty, System.Windows.DependencyObject, MS.Internal.FrameworkObject, int, bool, ref System.Windows.EffectiveValueEntry, out System.Windows.ValueLookupType, System.Windows.FrameworkElementFactory)
    System.Windows.StyleHelper.GetChildValue(System.Windows.UncommonField<System.Collections.Specialized.HybridDictionary[]>, System.Windows.DependencyObject, int, MS.Internal.FrameworkObject, System.Windows.DependencyProperty, ref MS.Utility.FrugalStructList<System.Windows.ChildRecord>, ref System.Windows.EffectiveValueEntry, out System.Windows.ValueLookupType, System.Windows.FrameworkElementFactory)
    System.Windows.StyleHelper.GetValueFromTemplatedParent(System.Windows.DependencyObject, int, MS.Internal.FrameworkObject, System.Windows.DependencyProperty, ref MS.Utility.FrugalStructList<System.Windows.ChildRecord>, System.Windows.FrameworkElementFactory, ref System.Windows.EffectiveValueEntry)
    System.Windows.StyleHelper.ApplyTemplatedParentValue(System.Windows.DependencyObject, MS.Internal.FrameworkObject, int, ref MS.Utility.FrugalStructList<System.Windows.ChildRecord>, System.Windows.DependencyProperty, System.Windows.FrameworkElementFactory)
    System.Windows.StyleHelper.InvalidatePropertiesOnTemplateNode(System.Windows.DependencyObject, MS.Internal.FrameworkObject, int, ref MS.Utility.FrugalStructList<System.Windows.ChildRecord>, bool, System.Windows.FrameworkElementFactory)
    System.Windows.FrameworkTemplate.InvalidatePropertiesOnTemplate(System.Windows.DependencyObject, object)
    ...
    [Aufrufliste abgeschnitten]

Innere Ausnahme 1:
KeyNotFoundException: Der angegebene Schlüssel war nicht im Wörterbuch angegeben.`

**Comment by sa-he** [comment] 2021-09-07 12:51
I can reproduce the exception when switching the context of a TabControl really fast. The exception does not occur always. Switching the TabControl context slowly never results in an error. It seems to be a timing issue.

**Comment by Psykobal** [comment] 2021-09-08 07:32
It's a bug from XAMLMarkupExtensions, an issue is already open there: https://github.com/XAMLMarkupExtensions/XAMLMarkupExtensions/issues/114

**Comment by konne** [comment] 2021-11-14 18:16
@Psykobal @sa-he @tobe83 should be fixed with 3.9.1
I will close this issue. If you still have an issue, just reopen.

**Closed by konne** 2021-11-14 18:16 UTC
